### ISSUE TITLE
Failed release results in inability to manage resources via terraform

### ISSUE THREAD

**Issue by andrewnazarov** [mumoshu/terraform-provider-helmfile#3]
Terraform apply ended with one failed release which broke the execution immediately. Some releases were installed successfully.

The subsequent run of `terraform plan` shows that the resource should be created as there is nothing installed:

```
# helmfile_release_set.mystack will be created
  + resource "helmfile_release_set" "mystack" {
      + apply_output      = (known after apply)
      + binary            = "helmfile"
      + dirty             = false
      + environment       = "staging"
      + helm_binary       = "helm"
      + id                = (known after apply)
      + path              = "git::https://******/helmfile.yaml"
      + working_directory = "."
    }
```

Now there are a bunch of releases left out of control of terraform. If I run `terraform apply` after that helmfile will deal with that situation, but I'm not sure that it's the intended behaviour.

Also, I noticed that logs produced by terraform apply (and helmfile apply) are not full and seem trimmed. There are much more releases that were installed successfully than shown in the output.

**Comment by andrewnazarov** [comment]
There is nothing related to `helmfile_release_set` in the TF state file.

**Comment by osterman** [comment]
> Also, I noticed that logs produced by terraform apply (and helmfile apply) are not full and seem trimmed

I wonder if terraform `outputs` have a max length?

**Comment by mumoshu** [comment]
> Now there are a bunch of releases left out of control of terraform.

@andrewnazarov Ideally, this shouldn't happen. But that's how it works today. The fundamental issue here is that `helmfile apply` doesn't fit the semantics of a terraform resource. A terraform resource should be updatable atomically, but `helmfile apply` is unable to treat your whole set of releases as an atomic unit.

Setting `atomic: true` and [`cleanupOnFail: true`](https://github.com/roboll/helmfile/pull/1005) on your releases alleviate the issue, as they result in undoing the failed release.

But that's not enough. What we need here is https://github.com/roboll/helmfile/issues/925, so that Helmfile reverts all the changes including successful releases before the failed one, which makes it look like atomic.

**Comment by andrewnazarov** [comment]
Ok, got the point. Gonna close this. And I could file a separate issue about the output later.
