### ISSUE TITLE
Document any information related to importing an existing environment

### ISSUE THREAD

**Issue by abatilo** [mumoshu/terraform-provider-helmfile#33]
If I've been using helmfile as a standalone tool, is there a way to smoothly transition ownership of those charts while using this plugin?

**Comment by mnatan** [comment]
Speaking from my personal experience as a user of this plugin:

It does not implement special "import" because during terraform "create", the released version is imported automatically.

I suggest:
1. apply a dummy helmfile on non-production Kubernetes cluster
2. apply it for the second time with this provider. 
3. make changes to the `values` file, terraform should print `helm diff` output during `terraform plan`.

If I'm right it should be safe to do with your existing deployments and this importing strategy should be documented in README.

**Comment by mumoshu** [comment]
@abatilo @mnatan Hey! Instead of the step 1 and 2, you can now run `terraform import helmfile_release_set.RESOURCE_NAME path/to/helmfile.yaml`. Please see https://github.com/mumoshu/terraform-provider-helmfile/tree/master/examples/importing-existing-helmfile-managed-releases#importing-existing-helmfile-project-into-terraform

**Comment by abatilo** [comment]
Thanks for that @mumoshu

Closing this issue now.
