### ISSUE TITLE
Environment `helm` used by default

### ISSUE THREAD

**Issue by andrewnazarov** [mumoshu/terraform-provider-helmfile#34]
I've noticed that if I don't specify an environment in my release_set, environment `helm` is used by default:

```
Generated command: wd = ., args = helmfile --environment helm --file helmfile-d3edf97a6b5b1af47bc97f073ab79a75bd9ba097852cd1c92386ad418473bd85.yaml --helm-binary helm --no-color diff --concurrency 0 --detailed-exitcode --suppress-secrets --context 3
```
Is this an expected behaviour? What is the reason for this?

I see some mentions here: https://github.com/mumoshu/terraform-provider-helmfile/blob/1207adb71daaa1a266d00d324d67aaca8069414a/pkg/helmfile/release_set.go#L38

**Comment by mumoshu** [comment]
@andrewnazarov Good job finding this one! I don't remember why I made the default environment "helm" anymore, so that changed it to "" in v0.4.1.

Please note that you'll need to explicitly set `environment = ""` in your tf file or remove `"environment": "helm",` from your tfstate if the old default is already persisted in your tfstate.

Any new release_sets created without `environment` should just work though.
