### ISSUE TITLE
Depends_on ignored

### ISSUE THREAD

**Issue by BuckinghamIO** [mumoshu/terraform-provider-helmfile#38]
When using Terraform with the Helmfile provider it completely ignores any depends on requirements.

In my instance I require this as some of my hooks actually setup credentials which are only available once the cluster is created. Since the Helmfile resource always try to generate a diff output regardless of the depends on requirement it fails every time on a fresh install unless I create Terraform and Helmfile seperately.

is there anyway I can work around this?

EDIT: the main cause of this issue is terraform plan also executes helmfile diff without taking into consideration if tiller is even present let alone if the cluster is even present

**Comment by mumoshu** [comment]
@BuckinghamIO It should generally work. How are you providing `KUBECONFIG` envvar or `kubeconfig_path` attribute to your helmfile_release_set resource? The release set resource is programmed to skip running helmfile-diff when kubeconfig_path is empty, because it is set to empty by `terraform plan`.

A working example is https://github.com/mumoshu/terraform-provider-eksctl/blob/master/examples/productionsetup-alb/testdata/01-bootstrap/main.tf#L155. In this example, `terraform plan` does work even before creating the eksctl_cluster, because the helmfile provider skips running `helmfile-diff` when `KUBECONFIG` is empty.

To be clear, even if it is declared as `KUBECONFIG = eksctl_cluster.blue.kubeconfig_path`, `terraform plan` evaluates it to `KUBECONFIG = ""` before creating the dependent eksctl_cluster. But the helmfile provider skips running `helmfile-diff` when it is empty, plan succeeds and works as expected.

**Comment by mumoshu** [comment]
In other words and from a developer's perspective, it is Terraform that ignores depends_on, not the provider. So we need to understand every real-world use-case and implenment a workaround for each so that the provider "looks" like understanding depends_on, even if Terraform doesn't support it.

**Comment by mumoshu** [comment]
@BuckinghamIO https://github.com/mumoshu/terraform-provider-helmfile/pull/42 may also fix your issue if this was due to that

**Comment by danil-fomichev** [comment]
@mumoshu here is a use-case example.

We would like to generate environment.yaml file with values imported from another modules and only after that run the helmfile_release_set resource.   Right now we cannot do this because the provider runs "helmfile diff" and it fails because the file doesn't exist.

**Comment by mumoshu** [comment]
@danil-fomichev How is `environment.yaml` used by your helmfile_release_set? An example `helmfile_release_set` definition would help!

**Comment by danil-fomichev** [comment]
@mumoshu it is included from helmfile.yaml:

```
bases:
- environment.yaml
```
obviously it must be generated before we run "helmfile diff".

The name of environment is specified in helmfile_release_set definition.

**Comment by mumoshu** [comment]
@danil-fomichev Gotcha! Thanks for clarifying. AFAIK, there's no way to make some terraform resource's "plan" operation optional depending on condition. https://github.com/mumoshu/terraform-provider-helmfile/issues/38#issuecomment-698883821

So the only way would be to enhance the provider to support something like `skip_diff_on_missing_files = ["path/to/environment.yaml"]` so that the provider can skip helmfile-diff before the files are generated somehow.

WDYT?

**Comment by danil-fomichev** [comment]
@mumoshu great idea!

**Comment by mumoshu** [comment]
@danil-fomichev Thanks for confirming! I'll give it a try

**Comment by mumoshu** [comment]
@BuckinghamIO Does the planned feature abovehttps://github.com/mumoshu/terraform-provider-helmfile/issues/38#issuecomment-723803997 look like to work for your use-case, too?

**Comment by mumoshu** [comment]
@danil-fomichev @BuckinghamIO `skip_diff_on_missing_files` is added since v0.10.0. Would you mind giving it a try?

**Comment by danil-fomichev** [comment]
@mumoshu Thank you so much!  When approximately do you plan to publish it to registry.terraform.io?

**Comment by mumoshu** [comment]
@danil-fomichev It should be available soon :) registry.terraform.io automatically syncs github releases so there should be nothing blocking that process on my end.

**Comment by danil-fomichev** [comment]
@mumoshu unfortunately it doesn't work as expected.

```
resource "helmfile_release_set" "infra" {
  depends_on            = [local_file.environment_file]
  working_directory     = var.helmfile_path
  environment           = var.environment.name
  kubeconfig            = var.kubeconfg_path
  environment_variables = local.environment_variables
  skip_diff_on_missing_files = [
    local_file.environment_file
  ]
}
```

it still runs 'helm diff' during 'terraform plan' and fails with error.

**Comment by danil-fomichev** [comment]
It works when I set absolute path to the file instead of 'local_file.environment_file'.  Not very nice looking code but it works.

**Comment by mumoshu** [comment]
@danil-fomichev Thanks for the feedback! I'll definitely enahnce it to work with relative paths. Stay tuned.

**Comment by mumoshu** [comment]
@danil-fomichev Since v0.10.1, it automatically coverts relative paths to absolute paths. Would you mind trying?

If it doesn't work as expected, try running terraform with `TF_LOG=TRACE terraform plan` so that you can see logs added in https://github.com/mumoshu/terraform-provider-helmfile/commit/b24131f943e2e64db2e897323771819d9397d285#diff-5cd325f86c36ad7da723fd859369712f88fe899ef97a4f3b286cda8f8625c6a9R12 for debugging
