### ISSUE TITLE
diff not working as expected

### ISSUE THREAD

**Issue by dudicoco** [mumoshu/terraform-provider-helmfile#7]
Hi,
@mumoshu, I came across a couple of issues:
When using ```helmfile_release``` no diff is being shown.
When using ```helmfile_release_set```with multiple releases, the diff being shown is only for one of the releases.

**Comment by abdennour** [comment]
Any update about this issue ?

**Comment by mumoshu** [comment]
I think I have never managed to reproduce this myself. Would you mind sharing the example project so that I can repro it myself?

**Comment by mumoshu** [comment]
Probably this is due to hitting some upper limit in Terraform on output value length.
I've recently added `json` (https://github.com/databus23/helm-diff/pull/226) and `simple` (https://github.com/databus23/helm-diff/pull/221) output formats, which is more compact. We would need to make it available via Helmfile to finally make the diff output compact enough for use in tf plan.

**Comment by mumoshu** [comment]
Also see #24

**Comment by mumoshu** [comment]
After some investigation, I came to conclusion that this and #24 are duplicates.

The issue should be fixed since v0.3.7.
@dudicoco @abdennour Would you mind confirming?

**Comment by dudicoco** [comment]
@mumoshu thanks for the update, I have not used the helmfile provider since first testing it, i'm using straight helmfile instead.

**Comment by mumoshu** [comment]
Okay then, I'll close this as resolved. But please feel free to reopen if it's still reproducible by either of you!

For anyone else, I'd suggest opening a separate issue if you see a similar issue, as it might be another one
